version: "3.8"

services:
  mongodb-prod:
    container_name: mongodb-prod
    image: mongo:4.4.4
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - hocus-pocus
    restart: always

  backend-prod:
    container_name: backend-prod
    image: minqiz/backend-prod:latest
    ports:
      - 8000:8000
    networks:
      - hocus-pocus

  frontend-prod:
    container_name: frontend-prod
    image: minqiz/frontend-prod:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - hocus-pocus

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8082:8082
    command: frontend-prod backend-prod --interval 300 --cleanup
    restart: always

networks:
  hocus-pocus:
    name: hocus-pocus
    driver: bridge