version: "3.8"

services:
  # backend-prod:
  #   build:
  #     context: ./backend
  #     args:
  #       - PORT=8000
  #       - MONGO_USER=${MONGO_USER}
  #       - MONGO_PASSWORD=${MONGO_PASSWORD}
  #       - MONGO_DB=${MONGO_DB}
  #       - JWT_SECRET=${JWT_SECRET}
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000

  frontend-prod:
    build:
      context: ./keyboard-music
      dockerfile: Dockerfile
    ports:
      - 80:80