name: Deploy

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    # env:
    #   PORT: ${{ secrets.PORT }}
    #   MONGO_USER: ${{ secrets.MONGO_USER }}
    #   MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    #   MONGO_DB: ${{ secrets.MONGO_DB }}
    #   JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and push Docker images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        docker-compose build frontend-prod && docker-compose push frontend-prod
        # docker-compose build backend-prod && docker-compose push backend-prod